plugins {
    id 'com.android.application'
}

android {
    namespace 'com.tcgrestock.monitor'
    compileSdk 35

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId "com.tcgrestock.monitor"
        minSdk 26
        targetSdk 34
        versionCode 7
        versionName "0.07"
    }

    def releaseKeystore = System.getenv("ANDROID_KEYSTORE_FILE")
    signingConfigs {
        if (releaseKeystore) {
            release {
                storeFile file(releaseKeystore)
                storePassword System.getenv("ANDROID_KEYSTORE_PASSWORD")
                keyAlias System.getenv("ANDROID_KEY_ALIAS")
                keyPassword System.getenv("ANDROID_KEY_PASSWORD")
                storeType "PKCS12"
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            if (releaseKeystore) {
                signingConfig signingConfigs.release
            }
        }
    }
}

dependencies {
    implementation 'androidx.core:core:1.15.0'
    testImplementation 'junit:junit:4.13.2'
}
